`timescale 1ns/1ps

module soc_top_level_interconnect (
    input  logic clk,
    input  logic rst_n,
    input  logic m0_awvalid,
    output logic m0_awready,
    output logic [63:0] m0_awaddr,
    input  logic m0_wvalid,
    output logic m0_wready,
    output logic [63:0] m0_wdata,
    output logic [7:0] m0_wstrb,
    output logic m0_bvalid,
    input  logic m0_bready,
    output logic m0_arvalid,
    output logic m0_arready,
    output logic [63:0] m0_araddr,
    output logic m0_rvalid,
    input  logic m0_rready,
    output logic [63:0] m0_rdata,
    input  logic s0_awvalid,
    output logic s0_awready,
    output logic [63:0] s0_awaddr,
    input  logic s0_wvalid,
    output logic s0_wready,
    output logic [63:0] s0_wdata,
    output logic [7:0] s0_wstrb,
    output logic s0_bvalid,
    input  logic s0_bready,
    output logic s0_arvalid,
    output logic s0_arready,
    output logic [63:0] s0_araddr,
    output logic s0_rvalid,
    input  logic s0_rready,
    output logic [63:0] s0_rdata,
    input  logic s1_awvalid,
    output logic s1_awready,
    output logic [31:0] s1_awaddr,
    input  logic s1_wvalid,
    output logic s1_wready,
    output logic [31:0] s1_wdata,
    output logic s1_bvalid,
    input  logic s1_bready,
    output logic s1_arvalid,
    output logic s1_arready,
    output logic [31:0] s1_araddr,
    output logic s1_rvalid,
    input  logic s1_rready,
    output logic [31:0] s1_rdata
);

endmodule
