`timescale 1ns/1ps

module l1_dcache_ctrl (
    input  logic clk,
    input  logic rst_n,
    output logic req_valid,
    output logic req_is_store,
    output logic [63:0] req_vaddr,
    output logic [63:0] req_store_data,
    output logic [7:0] req_store_be,
    output logic req_ack,
    output logic [63:0] req_load_data,
    output logic tlb_req,
    output logic [63:0] tlb_vaddr,
    output logic tlb_hit,
    output logic [55:0] tlb_paddr,
    output logic l2_bus_req,
    output logic [2:0] l2_bus_cmd,
    output logic [55:0] l2_bus_paddr,
    output logic [511:0] l2_bus_tx_data,
    output logic l2_bus_ack,
    output logic [511:0] l2_bus_rx_data,
    output logic tag_rd_en,
    output logic [5:0] tag_rd_idx,
    output logic [43:0] [0:3] tag_rd_tags,
    output logic [1:0] [0:3] tag_rd_mesi,
    output logic tag_wr_en,
    output logic [5:0] tag_wr_idx,
    output logic [1:0] tag_wr_way,
    output logic [43:0] tag_wr_tag,
    output logic [1:0] tag_wr_mesi,
    output logic data_rd_en,
    output logic [5:0] data_rd_idx,
    output logic [511:0] [0:3] data_rd_data,
    output logic data_wr_en,
    output logic [5:0] data_wr_idx,
    output logic [1:0] data_wr_way,
    output logic [63:0] data_wr_be,
    output logic [511:0] data_wr_data
);

endmodule
