`timescale 1ns/1ps

module rv32_id_ex_reg (
    input  logic clk,
    input  logic rst_n,
    output logic stall_i,
    output logic flush_i,
    output logic [31:0] pc_i,
    output logic [31:0] rs1_data_i,
    output logic [31:0] rs2_data_i,
    output logic [31:0] imm_i,
    output logic [4:0] rs1_addr_i,
    output logic [4:0] rs2_addr_i,
    output logic [4:0] rd_addr_i,
    output logic [1:0] op_a_sel_i,
    output logic [1:0] op_b_sel_i,
    output logic [3:0] alu_op_i,
    output logic [2:0] branch_type_i,
    output logic [1:0] jump_type_i,
    output logic mem_req_i,
    output logic mem_we_i,
    output logic [1:0] mem_size_i,
    output logic mem_unsigned_i,
    output logic wb_en_i,
    output logic [1:0] wb_sel_i,
    output logic illegal_instr_i,
    output logic [31:0] pc_o,
    output logic [31:0] rs1_data_o,
    output logic [31:0] rs2_data_o,
    output logic [31:0] imm_o,
    output logic [4:0] rs1_addr_o,
    output logic [4:0] rs2_addr_o,
    output logic [4:0] rd_addr_o,
    output logic [1:0] op_a_sel_o,
    output logic [1:0] op_b_sel_o,
    output logic [3:0] alu_op_o,
    output logic [2:0] branch_type_o,
    output logic [1:0] jump_type_o,
    output logic mem_req_o,
    output logic mem_we_o,
    output logic [1:0] mem_size_o,
    output logic mem_unsigned_o,
    output logic wb_en_o,
    output logic [1:0] wb_sel_o,
    output logic illegal_instr_o
);

endmodule
